#include "24s02ya__M24SR02.h"
#include <Wire.h>
void(* resetFunc) (void) = 0;
void nopuri()
{
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
}

nfcGadget::nfcGadget()
{
  if(!this->deviceConnected())
    resetFunc();

}

bool nfcGadget::deviceConnected()
{
  
  Wire.beginTransmission(0x2D); // Start I2C transmission to a device with given address
  if(!Wire.endTransmission())
    Wire.beginTransmission(0x56);
      if(!Wire.endTransmission())
        return true;
  return false;
}