#include "24s02ya__M24SR02.h"

void nopuri()
{
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
}

nfcGadget::nfcGadget()
{
  if(!this->deviceConnected())
    throw "eroare";
}

void nfcGadget::deviceConnected()
{
  
}