void(* resetFunc) (void) = 0;


void nopuri()
{
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
  asm volatile ("nop");  // Insert NOP instruction here
}